### PR TITLE
Fix error handling in AccessKeyForm

### LINKED ISSUE #112: Decryption errors are returned to client wrong
When testing earlier, we saw error message for decryption error wasn't showing properly. I reproduced this, but also found errors are working correct, by entering a fake access key. 

On the left is a bad access key:

- Error looks good
- error text is in "data". 
- code is numeric.
- Message is underscor case

On the right is decryption key error:
- Error lookgs bad
- data is null
- Code is underscore case 
- Message isa what should be displayed "Decryption failed."

Screenshot 2022-10-10 114729

### PR DESCRIPTION
**Pull request by Shelob9**
Fixes #112

### CODE REVIEW

File: src/components/AccessKeyForm.js [hunk 1]
```diff
@@ -158,7 +159,7 @@ const AccessKeyForm = ({ initialAccountId = null, minimal = false }) => {
           ) {
             setErrorMessage(err.data);
           } else {
-            setErrorMessage(__("An error happended."));
+            setErrorMessage(__("Unable to use access key."));
```
Comment (Shelob9) [inline src/components/AccessKeyForm.js:162]: @zackkatz This is the fall back message if response doesn't have a useable error message. I'm about to fix WHY this error was used, but if you want to have a different fallback message, let me know.

File: src/components/AccessKeyForm.js [hunk 2]
```diff
@@ -149,7 +149,7 @@ const AccessKeyForm = ({ initialAccountId = null, minimal = false }) => {
           if (
             err &&
             err.hasOwnProperty("message") &&
-            "message" === typeof err.message
+            "string" === typeof err.message
```
Comment (Shelob9) [inline src/components/AccessKeyForm.js:152]: Problem with this is it makes secret key error look bad, since now it is using the message property of error, not data, which is the human readable one, but was slug-cased in the decryption key error.
Screenshot 2022-10-10 122027

Comment (zackkatz) [reply src/components/AccessKeyForm.js:152]: Ideally, it'd use `data` first, then message.

```
{
    "code": 406,
    "message": "no_secret_ids",
    "data": "No secret ids found"
}
```

File: src/components/AccessKeyForm.js (hunk 1 above)
Comment (zackkatz) [reply src/components/AccessKeyForm.js:162]: "There was an error processing the access key."

Comment (Shelob9) [reply src/components/AccessKeyForm.js:162]: 👍

File: src/components/AccessKeyForm.js (hunk 2 above)
Comment (Shelob9) [reply src/components/AccessKeyForm.js:152]: @Shelob9 Yes, but beacuse message `data` is null, it will fall back to `message` which solves problem.

Comment (Shelob9) [reply src/components/AccessKeyForm.js]: 2f8036446c5cceca059d5a241abe42af0efd56f7da94107ffeb91cfd6a948d8f

**Comment by Shelob9** [comment]
@zackkatz Not sure why this wasn't merged
